import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import Background from "@/components/background/Background";
import "./globals.css";

export const metadata = {
  title: "White Mouse Developer",
  description: "WhiteMouseDev Generated by Kun Woo Kim",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Header />
        <Background />
        {children}
        <Footer />
      </body>
    </html>
  );
}
